### ISSUE TITLE
Problems with missing record fields

### ISSUE THREAD

**Issue by gandy92** [ravid7000/table-sortable#13]
My API delivers data where individual records may have missing fields, e.g.
```
[
  {id:1, a: "a1", b:"b4", c:"c1", best_before:"2021-03-21"},
  {id:2, a: "a2", b:"b3", c:"c2", best_before:"2020-11-02"},
  {id:3, a: "a3", b:"b1", c:"c3"},
  {id:4, a: "a4", b:"b2", c:"c4", best_before:"2025-01-01"},
]
```
Trying to sort the last column results in the error message 'TableSortable Violation: dataset.sort Column name "best_before" does not exist in collection', if the first row contains a missing field in the sort row. The following steps show what happens:
* sorting "best_before" yields rows 2-1-4-3 (ascending)
* sorting "best_before" again yields 3-4-1-2 (descending)
* sorting "best_before" once more yields said error message, leaving the sort order unchanged (expecting ascending order)
* sorting "a" restores the rows to 1-2-3-4
* sorting "b" yields 3-4-2-1
* sorting "best_before" yields said error message, leaving the sort order unchanged (expecting ascending order)

Another problem arises, if I choose "best_before" to not be the last column. In this case, all values from columns right of "best_before" shift one to the left. Instead, I'd expect the cell to be empty.

Is there an easy way to fix this? Maybe by providing fall-back values for missing elements?

**Comment by arobert3434** [comment]
Handling this in tablesortable would add overhead, code complexity, or both. I'd rather vote for a documentation update here to state that it expects all fields to be filled (even with null).

**Comment by ravid7000** [comment]
Make your api to add `null` for missing fields. TableSortable expects all fields available in the data.
