### ISSUE TITLE
using table-sortable with Firebase Database

### ISSUE THREAD

**Issue by inglesuniversal** [ravid7000/table-sortable#2]
I tested your script on PHP... worked fine...

Now using Firebase, I was able to dump the array to a web storage value, but I don't know how I can paste it as part of the code dynamically without any intervention from user.

Can this be done?

Regards

**Comment by ravid7000** [comment]
On version 2.0.0
See the documentation to dynamic update data on table: https://table-sortable.now.sh/story-latest.html#setData
